export enum ProcessState {
    SUCCESS,
    ERR_FNAME,
    ERR_PASSWD,
    ERR_ISBN,
    ERR_ID,
    ERR_COLLE,
    ERR_ISBN_DUPL,
    ERR_ID_DUPL,
    ERR_COLLE_DUPL,
    ERR_ARGS_ALGO,
    ERR_ARGS_PASSWD,
    ERR_ARGS_FNAME,
    ERR_ARGS_BOOK,
    ERR_ARGS_ID,
    ERR_ARGS_COLLE,
    ERR_UNKNOWN_CMD,
}
export const CodeMessage = {
    [ProcessState.SUCCESS]: 'SUCCESS',
    [ProcessState.ERR_FNAME]: 'ERR_FNAME',
    [ProcessState.ERR_PASSWD]: 'ERR_PASSWD',
    [ProcessState.ERR_ISBN]: 'ERR_ISBN',
    [ProcessState.ERR_ID]: 'ERR_ID',
    [ProcessState.ERR_COLLE]: 'ERR_COLLE',
    [ProcessState.ERR_ISBN_DUPL]: 'ERR_ISBN_DUPL',
    [ProcessState.ERR_ID_DUPL]: 'ERR_ID_DUPL',
    [ProcessState.ERR_COLLE_DUPL]: 'ERR_COLLE_DUPL',
    [ProcessState.ERR_ARGS_ALGO]: 'ERR_ARGS_ALGO',
    [ProcessState.ERR_ARGS_PASSWD]: 'ERR_ARGS_PASSWD',
    [ProcessState.ERR_ARGS_FNAME]: 'ERR_ARGS_FNAME',
    [ProcessState.ERR_ARGS_BOOK]: 'ERR_ARGS_BOOK',
    [ProcessState.ERR_ARGS_ID]: 'ERR_ARGS_ID',
    [ProcessState.ERR_ARGS_COLLE]: 'ERR_ARGS_COLLE',
    [ProcessState.ERR_UNKNOWN_CMD]: 'ERR_UNKNOWN_CMD',
};
